### ISSUE TITLE
Move JavaScriptRoom.github.io to chat.js.org

### ISSUE THREAD

**Issue by 7fe** [JavaScriptRoom/JavaScriptRoom.github.io#5]
The chat.js.org domain is on the `cnames_restricted.js` list.  So this may or not be approved depending on the discussion [here](https://github.com/js-org/dns.js.org/issues/1898).  http://dns.js.org makes it clear that this is its intended use.

Right now the page http://javascriptroom.github.io/rules is up and activately used.

Index.html will hopefully eventually link to the actually site through a redirect.  I have requested a pull request for [that](https://github.com/JavaScriptRoom/JavaScriptRoom.github.io/pull/4/commits/d73c7edcf20dfefa624b62797e00b8a41e84b0b6).  I believe this is a valid and useful use of the http://chat.js.org link.  

Yeah or nah?

**Comment by Zirak** [comment]
why?

**Comment by 7fe** [comment]
@Zirak might make the room more popular.  Certainly easier to remember the url.

**Comment by loktar00** [comment]
Maybe it's my fault for pulling a Neal and making http://room17.chat one night when were all talking about domain names? It just forwards to the chat.... Seems like this was a direct result of that night

Joking about the Neal thing, but you can pay $5 to publish on my blog /s

**Comment by ctrldavid** [comment]
I vote for `towc.js.org`

**Comment by Zirak** [comment]
@limeblack Easier for who? SO goers have the rooms list or the sidebar. Maybe random internet people randomly typing "I wonder where chat.js.org goes"

**Comment by ssube** [comment]
I feel like there's a little bit of difference between a single joke domain owned by an RO and associating the room (and SO) with a third-party project that doesn't go into any detail as to who they are, what they do, or why. What else do they link to? Do we trust the maintainer?

**Comment by darkyen** [comment]
Idiomatically, https://chat.js.org  should represent a chat that the _js community_ agrees upon not just a random bunch ran chatroom. We are not the _standard_ js chat, nor do we understand the goal of the project as ssube mentioned.

**Comment by 7fe** [comment]
@darkyen by my very accurate estimation it is likely the most activate js chat in the world.  Freenode maybe but it is a hassle to use.

**Comment by Zirak** [comment]
I mean, it doesn't really matter methinks. You can link anywhere if you want, it's your dime. But suppose `chat.js.org` links to the room, what happens next? Besides cracking the champagnes?

**Comment by darkyen** [comment]
@limeblack any chatroom for any reasonably popular js project will outdo us, for example check out socket.io's chat.

**Comment by 7fe** [comment]
@darkyen You mean the [demo chat](https://socket.io/demos/chat/) or the freenode socket.io chat(Again freenode isn't what I call an ideal chat platform for newcomers.  There is no history with out installing software)?  Again our chat room caters to all types of users.  Linking to a specific library chat doesn't make sense.

**Comment by darkyen** [comment]
@limeblack  

> Again our chat room caters to all types of users. 

There is a huge problem with that approach, for instance do you know anything about nodejs internals, how about eshttp internals, how about * js platform that runs on 48k RAM embedded systems? 

_chat.js.org_ is not _*.js.org_

The domain suggest that it would be to discuss the JS Spec and nothing else, which we barely do, instead our room is a popurrie of js discussions mixed with literally anything from porn to personal life telecasts. 

Furthermore, chat.stackoverflow barely is a good chat platform something like a proper slack group is going to go miles ahead in being a proper JS chat hub.

**Comment by darkyen** [comment]
Btw, I like your idea of a standard js room/group, I just don't like the idea of this room being the standard js room.

**Comment by 7fe** [comment]
@darkyen Slack is technically a paid service.  Yes you can get invite to get around this but it is not acceptable to the average person.

**Comment by tentonaxe** [comment]
There's also a number of discord servers with good followings... and i'm not sure we really need more popularity, we get quite a large amount of traffic as it is
